### PR TITLE
Hello Microverse Project

### PR DESCRIPTION
**Pull request by MmakolaMC**
Added the .github folder with the linters.yml file in it.
Added the .ignore file ignoring node_modules/ and the test.md file.
Added an index.html and a style.css files.
Added .hintrc and .stylelintrc.json files

### CODE REVIEW

**Review by OLIPLICHE — CHANGES_REQUESTED** [review]
Hi @MmakolaMC , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- README file is descriptive 👏
- Commit messages are meaningful 👏 👏
Github flow is correctly used (Pull Request is made from the feature branch into the main branch) 👏

## Required Changes ♻️

- [ ] Please set up Linter correctly for this repository. Here is the Link: [Linters Config](https://github.com/microverseinc/linters-config/tree/master/html-css)
- [ ] Please add a descriptive **Title** in your Pull  Request telling you what changes are inside.
- [ ] Please make sure that the Pull Request have a short summary describing introduced changes in more detail.
- [ ] Please create a `.gitignore` file and add inside of it the `node_modules` folder  and `test.md` file. 
- [ ] Important: Please, you can go back to the Project requirements. here is the [LINK](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @MmakolaMC, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

200w

 ## Highlights
✔️ Great job in making the changes so far

 ## Required Changes ♻️
- [x] Kindly set up Linters correctly from [here](https://github.com/microverseinc/linters-config/tree/master/html-css). Make sure that all checks are passing and have a blue tick.
 _You can try removing and then pasting the files again to make sure linters are running._
- [x]  Kindly rename the Title in your Pull Request to `Hello Microverse Project` instead of `Add necessary files to repo`. It will show clearly what you have worked on the pull request by telling you what changes are inside.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MmakolaMC** [comment]
@sja-thedude I am a bit confused now in regards to my title, the first reviewer advised that I put a descriptive title to reflect the changes in the feature branch and the title you advised I use is not reflective of the changes in the feature branch but more like a pointer to the project/repo. which of the two is a standard way of doing things so I can avoid this in the future?

The linters are running fine in my local environment(vscode), so when you say I should try to remove and paste the files do you mean editing the files and making new commits or deleting the files from the repo and starting the process all over?

**Comment by sja-thedude** [comment]
> @sja-thedude I am a bit confused now in regards to my title, the first reviewer advised that I put a descriptive title to reflect the changes in the feature branch and the title you advised I use is not reflective of the changes in the feature branch but more like a pointer to the project/repo. which of the two is a standard way of doing things so I can avoid this in the future?
> 
> 
> 
> The linters are running fine in my local environment(vscode), so when you say I should try to remove and paste the files do you mean editing the files and making new commits or deleting the files from the repo and starting the process all over?

Hi @MmakolaMC!
I have suggested you to add descriptive PR Title which is Hello Microverse Project. This title shows what is worked on inside the project.

Linters should pass all the checks and blue tick should be displayed on the pull request. This will happen when linters are setup correctly. For this to work you should remove all the linter files and then paste them again.

**Review by Danieldotcomcoder — APPROVED** [review]
Hello @MmakolaMC, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 👍 👍 😄 👏 

Congratulations! 🎉 🎉 🎉 

comp-2
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MmakolaMC** [comment]
Thanks a lot for the guidance and patience, much appreciated!

**Pull request merged**
